[package]
name = "teaplc"
version = "0.1.0"
edition = "2021"

[build-dependencies]
lalrpop = "0.22.0"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
indexmap = "2.7.0"
lalrpop-util = { version = "0.21.0", features = ["lexer", "unicode"] }
thiserror = "2.0.12"
